version: "3.7"

services:
  luban-doc-v1:
    build: .
    container_name: luban-doc-v1
    expose:
      - "80"
    networks:
      - proxy
    environment:
      - "PORT=80"
      - "NODE_ENV=production"
    command: npm run serve
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doc-v1.entrypoints=websecure"
      - "traefik.http.routers.doc-v1.rule=Host(`1x.luban.fun`)"

networks:
  proxy:
    external: true