version: "3.3"

services:
  luban-doc-v1:
    build: .
    container_name: luban-doc-v1
    expose:
      - "80"
    environment:
      - "PORT=80"
      - "NODE_ENV=production"
    command: npm run serve
    labels:
      - "traefik.http.routers.ssr.entrypoints=websecure"
      - "traefik.http.routers.ssr.rule=Host(`1x.luban.fun`)"